export const menuItems = [
  {
    title: "Departments",
    submenu: [
      {
        title: "Deals",
        submenu: [
          { title: "Deals" },
          { title: "Shop All Deals" },
          { title: "Home" },
          { title: "School & Office Supplies" },
          { title: "Clothing & Accessories" },
          { title: "Electronics" },
          { title: "Kitchen & Dining" },
          { title: "Patio & Garden" },
          { title: "Beauty" },
          { title: "Pets" },
          { title: "Toys" },
          { title: "Stock-Up Essentials" },
          { title: "Food" },
          { title: "Baby" },
          { title: "Wellness & Personal Care" },
          { title: "Kids" },
          { title: "Sports & Outdoors" },
          { title: "Home Improvement" },
          { title: "Seasonal Décor" },
          { title: "Outdoor Play" },
          { title: "Household Essentials" },
          { title: "Auto" },
          { title: "Video Games" },
          { title: "Books, Movies & Music" },
        ],
      },
      {
        title: "Mother's Day",
        submenu: [
          { title: "Shop All" },
          { title: "Flowers" },
          { title: "Greeting Cards" },
          { title: "Gift cards & E-Gift Cards" },
          { title: "Food Gifts" },
          { title: "Gift Sets" },
          { title: "Jewelry & Fashion" },
          { title: "Beauty & Spa" },
          { title: "Home" },
          { title: "Tech" },
          { title: "Patio & Garden" },
          { title: "Sports & Outdoor" },
          { title: "Photo & Personalized Gifts" },
          { title: "Lego & Games" },
          { title: "Kitchen & Dining" },
          { title: "Pet Moms" },
          { title: "Art & Crafts" },
          { title: "New Moms" },
          { title: "Plush & Novelty Gifts" },
          { title: "Group Gifts" },
          { title: "Mom Owned Brands" },
        ],
      },
      {
        title: "Graduation",
        submenu: [
          { title: "Shop All Graduation" },
          { title: "Graduation Gifts" },
          { title: "Graduation Dresses" },
          { title: "Graduation Men's Outfits" },
          { title: "Greeting Cards" },
          { title: "Party Food" },
          { title: "Party Supplies" },
        ],
      },
      {
        title: "Summer Shop",
        submenu: [
          { title: "New and trending this season" },
          { title: "New in Beauty" },
          { title: "The Swim Shop" },
          { title: "The Dress Edit" },
          { title: "Summer Home Trend" },
        ],
      },
      {
        title: "Grocery",
        submenu: [
          { title: "Shop All" },
          { title: "Mother's Day" },
          { title: "Flower Shop" },
          { title: "Recipes" },
          { title: "Everyday Meals" },
          { title: "Fresh Food" },
          { title: "Grocery & Essentials" },
          { title: "Spring Grilling" },
          { title: "Summer Gatherings" },
        ],
      },
      {
        title: "Home, Garden & Tools",
        submenu: [
          { title: "Shop All Home" },
          { title: "Shop All Home Improvement" },
          { title: "Shop All Patio & Garden" },
          { title: "Spring Savings" },
          { title: "Home Spring Savings" },
          { title: "Home Improvement Spring Savings" },
          { title: "Patio & Garden Spring Savings" },
          { title: "Featured" },
          { title: "Emergency Prep" },
          { title: "Everyday DIY for Less" },
          { title: "Home Improvement Services" },
          { title: "Home New & Trending" },
          { title: "Moving Center" },
          { title: "Registry" },
          { title: "Shop By Room" },
          { title: "Shop By Style" },
          { title: "Spring Home Trends" },
          { title: "Spring Outdoor Refresh" },
          { title: "Summer Style" },
          { title: "Bath" },
          { title: "Shop All" },
          { title: "Bathroom Accessories" },
          { title: "Bathroom Rugs & Bath Mats" },
          { title: "Shower Curtains & Accessories" },
          { title: "Shower Heads" },
          { title: "Toilets & Bid" },
        ],
      },
      {
        title: "Electronics & Video Games",
        submenu: [
          { title: "Shop all Electronics" },
          { title: "Shop all Video Games" },
          { title: "Deals" },
          { title: "Tech Deals" },
          { title: "Video Game Deals" },
          { title: "New & Trending" },
          { title: "Trending Tech" },
          { title: "New in Video Games" },
          { title: "TV & Home Theater" },
          { title: "Shop all TVs" },
          { title: "TVs by Size" },
          { title: "Smart TVs" },
          { title: "Roku TVs" },
          { title: "Streaming" },
          { title: "TV Mounts & Accessories" },
          { title: "Shop All Home Theater" },
          { title: "Sound Bars" },
          { title: "Projectors" },
          { title: "Portable Audio" },
          { title: "Shop all Headphones" },
          { title: "Shop all Speakers" },
          { title: "Smart Home" },
          { title: "Shop All Smart Home" },
          { title: "Smart Home Security" },
          { title: "Tablets" },
          { title: "Shop All Tablets" },
          { title: "iPad" },
          { title: "Android Tablets" },
          { title: "Walmart Restored Tablets" },
          { title: "Tablet Accessories" },
        ],
      },

      {
        title: "Beauty",
        submenu: [
          { title: "Deals" },
          { title: "Walmart Style" },
          { title: "BeautySpaceNK" },
          { title: "Walmart Start" },
          { title: "Curly Hair & More Store" },
          { title: "Brands we love" },
          { title: "Shop Brands A-Z" },
          { title: "L’Oreal Hyaluron Pure" },
          { title: "Goody Tru" },
          { title: "Madison Reed" },
          { title: "CeraVe" },
          { title: "Slip" },
          { title: "Revolution Beauty" },
          { title: "Mario Badescu" },
          { title: "e.l.f. Cosmetics" },
        ],
      },
      {
        title: "Sports & Outdoors",
        submenu: [
          { title: "Shop all Sports & Outdoors" },
          { title: "Deals" },
          { title: "Shop all" },
          { title: "Clearance" },
          { title: "Exercise & Fitness" },
          { title: "Shop all Exercise & Fitness" },
          { title: "Cardio Equipment" },
          { title: "Fitness Accessories" },
          { title: "Strength Training" },
          { title: "Treadmills" },
          { title: "Sports" },
          { title: "Shop all Sports" },
          { title: "Baseball" },
          { title: "Basketball" },
          { title: "Football" },
          { title: "Golf" },
          { title: "Pickleball" },
          { title: "Soccer" },
          { title: "Softball" },
          { title: "Tennis" },
          { title: "Sports Fan Shop" },
        ],
      },
      {
        title: "Movies, Music & Books",
        submenu: [
          { title: "Shop all Movies & TV shows" },
          { title: "Movie & TV Show Deals" },
          { title: "Preorder Movies & TV shows" },
          { title: "4K Ultra HD Movies" },
          { title: "Blu-ray Movies" },
          { title: "DVD Movies" },
          { title: "TV Shows on 4K Ultra HD" },
          { title: "TV Shows on Blu-ray" },
          { title: "TV Shows on DVD" },
          { title: "Music" },
          { title: "Shop all Music" },
          { title: "Music Deals" },
          { title: "Preorder Music" },
          { title: "Vinyl Records" },
          { title: "Turntables" },
          { title: "Rap & hip-hop" },
          { title: "Rock" },
          { title: "Pop" },
          { title: "Country" },
          { title: "Classical" },
        ],
      },
      {
        title: "Gift Cards",
        submenu: [
          { title: "eGift Cards" },
          { title: "Plastic Gift Cards" },
          { title: "Bulk & Corporate Gift Cards" },
          { title: "Cards by Occasion" },
          { title: "Mother's Day" },
          { title: "Father's Day" },
          { title: "Graduation" },
          { title: "Spring" },
          { title: "Birthday" },
          { title: "Thank you" },
          { title: "Congratulations" },
          { title: "Just Because" },
          { title: "Baby Shower" },
          { title: "Wedding" },
        ],
      },
    ],
  },
  {
    title: "Services",
    submenu: [
      {
        title: "Auto Care Center Services",
        submenu: [
          { title: "Auto Care Center Services" },
          { title: "Buy Tires & Schedule Installation" },
          { title: "Tire Maintenance" },
          { title: "Schedule an Oil Change" },
          { title: "Vehicle Maintenance" },
          { title: "Virtual Garage" },
          { title: "Find an Auto Care Center" },
        ],
      },
      {
        title: "Walmart+ Membership",
        submenu: [
          { title: "Free delivery from stores" },
          { title: "Free shipping with no order minimum" },
          { title: "Member prices on fuel" },
          { title: "Video streaming" },
          { title: "Walmart+ Travel" },
        ],
      },
      {
        title: "Photo Services",
        submenu: [
          { title: "Photo Center" },
          { title: "Prints" },
          { title: "Cards" },
          { title: "Gifts" },
          { title: "Pet Gifts" },
          { title: "Same Day Photos & Gifts" },
        ],
      },
      {
        title: "Financial Services",
        submenu: [
          { title: "Money Center" },
          { title: "Walmart Pay" },
          { title: "Credit & Debit" },
          { title: "Capital One Walmart Rewards" },
          { title: "One Debit Card" },
          { title: "Walmart MoneyCard" },
          { title: "Green Dot" },
          { title: "Reloadable Debit Cards" },
          { title: "Buy Now, Pay Later" },
          { title: "Affirm" },
          { title: "Money Services" },
          { title: "Bill Payment" },
          { title: "Check Cashing" },
          { title: "Check Printing" },
          { title: "Load & Unload" },
          { title: "Money Orders" },
          { title: "Money Transfers" },
          { title: "Tax Preparation" },
        ],
      },
      {
        title: "Protection, Home, & Tech",
        submenu: [
          { title: "Walmart Protection Plans" },
          { title: "AppleCare" },
          { title: "Home & Tech Services" },
          { title: "Assembly, Home Improvement, & Installation Services" },
          { title: "Home heating & A/C installation" },
          { title: "Tech Services" },
        ],
      },
      {
        title: "Subscriptions",
        submenu: [
          { title: "Subscriptions Home" },
          { title: "Manage Subscriptions" },
          { title: "Create a Walmart Account" },
        ],
      },
      {
        title: "Community & Giving",
        submenu: [
          { title: "Support a local charity" },
          { title: "Access nonprofit resources" },
          { title: "Built for Better" },
          { title: "Shop Black owned brands" },
          { title: "Shop women owned brands" },
        ],
      },
      {
        title: "Ordering Online",
        submenu: [
          { title: "Pickup & delivery" },
          { title: "SNAP EBT" },
          { title: "Substitutions" },
          { title: "Subscriptions" },
          { title: "Stay Informed" },
          { title: "Discover the app" },
          { title: "Store Mode" },
          { title: "Sign up for trends & savings" },
          { title: "Recipe Library" },
          { title: "Walmart Live" },
          { title: "#IYWYK" },
        ],
      },
    ],
  },
  {
    title: "Deals",
  },
  { title: "Grocery & Essentials" },
  { title: "Mother's Day" },
  { title: "Teacher Appreciation" },
  { title: "Graduation" },
  { title: "National Pet Month" },
  { title: "Home" },
  { title: "Fashion" },
];
